FROM ghcr.io/astral-sh/uv:python3.13-alpine

WORKDIR /app

COPY pyproject.toml .
COPY uv.lock .

RUN uv sync --locked

ADD ./todo_backend/ ./todo_backend/

CMD ["uv", "run", "-m", "todo_backend.main"]