FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /app

COPY Server .

RUN dotnet publish -c Release --runtime linux-x64 -o publish/ --self-contained false


FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime

ARG PORT=8001

EXPOSE ${PORT}

ENV ASPNETCORE_HTTP_PORTS=${PORT}

ENV PING_SHARED_FILE='/tmp/ping'

WORKDIR /app

COPY --from=build /app/publish/ .

CMD ["dotnet", "Server.dll"]
